services:
  - type: web
    name: bun-app
    env: node
    plan: free
    buildCommand: bun install
    startCommand: bun run index.ts
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production